import subprocess

Import("env")

build_root = Dir("../..").abspath
build_current = Dir(".").abspath
src_root = Dir(".").srcnode().abspath
src_configure = Dir("configure").srcnode().abspath
scons_root = Dir("#").abspath

cwd = os.getcwd()
os.chdir(build_current)
subprocess.run([src_configure], check=True)
